In [0]:
import pandas as pd
import numpy as np

# Series Object

In [2]:
data = pd.Series([0.25,0.5,0.75,1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [3]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [4]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
print(data[1])
print(data[1:3])

0.5
1    0.50
2    0.75
dtype: float64

## Series a generalized Numpy array
The essential difference is the presence of the index: while the NumPy array has an implicitly defined integer index used to access the values, the Pandas Series has an explicitly defined index associated with the values.

In [6]:
data = pd.Series(np.linspace(.25,1,4),index=['a','b','c','d'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [7]:
data['b']

0.5

In [8]:
data = pd.Series(np.linspace(.25,1,4),index = [2,5,3,7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [9]:
data[5]

0.5

## Series as Python dict

In [10]:
population_dict = {
    'California': 38332521,
    'Texas': 26448193,
    'New York': 19651127,
    'Florida': 19552860,
    'Illinois': 12882135
} 
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [11]:
print(population['California'])
print(population['California':'Illinois'])

38332521
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

## Constructing Series Object

In [12]:
pd.Series(data.values,index = np.arange(0,4))

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [13]:
pd.Series(np.arange(0,5))

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [14]:
pd.Series(6,np.arange(0,4))

0    6
1    6
2    6
3    6
dtype: int64

In [15]:
pd.Series(population_dict)

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [16]:
pd.Series({2:'a',1:'b',3:'c'},index = [3,2])

3    c
2    a
dtype: object

# DataFrame Object

## DataFrame as a generalized NumPy array

In [0]:
area_dict = {
    'California': 423967,
    'Texas': 695662,
     'New York': 141297,
    'Florida': 170312,
    'Illinois': 149995
}
area = pd.Series(area_dict)
states = pd.DataFrame({'population':population, 'area':area})
# the same result can give
#states = pd.DataFrame({'population':population_dict,'area':area_dict})

In [18]:
states

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [19]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [20]:
states.columns

Index(['population', 'area'], dtype='object')

 DataFrame maps a column name to a Series of column data.

In [21]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

## Constructing DataFrame Objects

From Single Series Object

In [22]:
pd.DataFrame(population,columns = ['population'])

            population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

From a list of Dicts

In [23]:
data = [ {'a':idx,'b':idx * 2}  for idx in range(10)]
print(pd.DataFrame(data))


#even if some keys is missing
print(pd.DataFrame([{'a':1,'b': 2},{'b':3,'c':4}]))

   a   b
0  0   0
1  1   2
2  2   4
3  3   6
4  4   8
5  5  10
6  6  12
7  7  14
8  8  16
9  9  18
     a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

## Index as immutable array

In [0]:
ind = pd.Index([2,3,5,7,11])

In [25]:
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [26]:
ind[1],ind[::2]

(3, Int64Index([2, 5, 11], dtype='int64'))

In [27]:
print(ind.size,ind.shape,ind.ndim,ind.dtype)

5 (5,) 1 int64

In [28]:
ind[1] = 0

TypeError: ignored

## Index as ordered set

In [29]:
indA = pd.Index([1,3,5,7,9])
indB = pd.Index([2,3,5,7,11])
indA & indB,indA | indB,indA ^ indB

(Int64Index([3, 5, 7], dtype='int64'),
 Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64'),
 Int64Index([1, 2, 9, 11], dtype='int64'))

## Data Selection in Series
Series as dictionary

In [30]:
import pandas as pd
data = pd.Series([0.25,0.5,0.75,1.0],index = ['a','b','c','d'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [31]:
print(data['b'])
print('a' in data)
print(data.keys())
list(data.items())

0.5
True
Index(['a', 'b', 'c', 'd'], dtype='object')

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

This easy mutability of the objects is a convenient feature: under the hood, Pandas is making decisions about memory layout and data copying that might need to take place; the user generally does not need to worry about these issues.

In [32]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

Series as one-dimensional
when you are slicing with an explicit index (i.e., data['a':'c']), the final index is included in the slice, while when you’re slicing with an implicit index (i.e., data[0:2]), the final index is excluded from the slice.

In [33]:
print(data['a':'c']),
print(data[:2])
#masking
print(data[(data > 0.3) & (data < 0.8)])
#fancy indexing 
print(data[['a','e']])

a    0.25
b    0.50
c    0.75
dtype: float64
a    0.25
b    0.50
dtype: float64
b    0.50
c    0.75
dtype: float64
a    0.25
e    1.25
dtype: float64

### Indexers loc,iloc,ix
 if your Series has an explicit integer index, an indexing operation such as data[1] will use the explicit indices, while a slicing operation like data[1:3] will use the implicit Python-style index.

In [34]:
data = pd.Series(['a','b','c'],index = [1,3,5])
data

1    a
3    b
5    c
dtype: object

In [35]:
#explicit
data[1]

'a'

In [36]:
#implicit
data[1:3]

3    b
5    c
dtype: object

__loc__ attribute allows indexing and slicing that always references the explicit index:

In [37]:
data.loc[1],data.loc[1:3]

('a', 1    a
 3    b
 dtype: object)

__iloc__ attribute allows indexing and slicing that always references the implicit Python-style index:

In [38]:
data.iloc[1],data.iloc[1:3],data.iloc[1:3]

('b', 3    b
 5    c
 dtype: object, 3    b
 5    c
 dtype: object)

third indexing attribute, ix, is a hybrid of the two, and for Series objects is equivalent to standard []-based indexing. The purpose of the ix indexer will become more apparent in the context of DataFrame objects, which we will discuss in a moment

# Data Selection in DataFrame

## DataFrame as a dictionary

In [0]:
states = pd.DataFrame({'population':population, 'area':area})

In [40]:
states['area'] is states.area

True

In [0]:
states['density'] = states['population']/states['area']

In [42]:
states

            population    area     density
California    38332521  423967   90.413926
Texas         26448193  695662   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763

In [43]:
states.values

array([[3.83325210e+07, 4.23967000e+05, 9.04139261e+01],
       [2.64481930e+07, 6.95662000e+05, 3.80187404e+01],
       [1.96511270e+07, 1.41297000e+05, 1.39076746e+02],
       [1.95528600e+07, 1.70312000e+05, 1.14806121e+02],
       [1.28821350e+07, 1.49995000e+05, 8.58837628e+01]])

In [44]:
states.T

              California         Texas  ...       Florida      Illinois
population  3.833252e+07  2.644819e+07  ...  1.955286e+07  1.288214e+07
area        4.239670e+05  6.956620e+05  ...  1.703120e+05  1.499950e+05
density     9.041393e+01  3.801874e+01  ...  1.148061e+02  8.588376e+01

[3 rows x 5 columns]

In [45]:
states.values[0]

array([3.83325210e+07, 4.23967000e+05, 9.04139261e+01])

In [46]:
states['population']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: population, dtype: int64

In [47]:
states.iloc[:3,:2]

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297

In [48]:
states.loc[:'Illinois',:'area']

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [49]:
states.loc[states.density > 100,['population','density']]

          population     density
New York    19651127  139.076746
Florida     19552860  114.806121

## Additional indexing conventions

While indexing refers to columns, slicing refers to rows:

In [50]:
states['Florida':'Illinois']

          population    area     density
Florida     19552860  170312  114.806121
Illinois    12882135  149995   85.883763

# Operating on Data in Pandas

## Ufuncs: Index Preservation

In [0]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0,10,4))

In [52]:
ser

0    6
1    3
2    7
3    4
dtype: int64

In [53]:
df = pd.DataFrame(rng.randint(0,10,(3,4)), columns = ['A','B','C','D'])
df

   A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [54]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [55]:
np.sin(df*np.pi/ 4)

          A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

## UFuncs: Index Alignment

### Index alignment in Series

In [0]:
 area = pd.Series({'Alaska': 1723337, 
                    'Texas': 695662,                        
                  'California': 423967}, name='area')       
 population = pd.Series({'California': 38332521, 'Texas': 26448193,                    
                         'New York': 19651127}, name='population')

In [57]:
population/area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [58]:
area.index | population.index

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [59]:
population.div(area,fill_value = 1)

Alaska        5.802696e-07
California    9.041393e+01
New York      1.965113e+07
Texas         3.801874e+01
dtype: float64

In [60]:
A = pd.Series([2, 4, 6], index=[0, 1, 2]) 
B = pd.Series([1, 3, 5], index=[1, 2, 3]) 
A.add(B,fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

### Index alignment in DataFrame

Notice that indices are aligned correctly irrespective of their order in the two objects, and indices in the result are sorted.

In [61]:
 A = pd.DataFrame(rng.randint(0, 20, (2, 2)),                         
                  columns=list('AB')) 
 B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
                  columns=list('BAC')) 
print(A)
print(B)

   A   B
0  1  11
1  5   1
   B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [62]:
A + B

      A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [63]:
fill = A.stack().mean()
A.add(B,fill_value = fill)

      A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5

## Operating on Null Values

### Detecting null values

In [0]:
data = pd.Series([1,np.nan,'hello',None])

In [65]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [66]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [67]:
data[data.notnull()]

0        1
2    hello
dtype: object

### Droppping null values

In [68]:
data.dropna()

0        1
2    hello
dtype: object

In [69]:
df = pd.DataFrame([[1,np.nan,2],
                   [2,3,5],
                   [np.nan,4,6]])
df

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

By default, dropna() will drop all rows in which any null value is present:

In [70]:
df.dropna()

     0    1  2
1  2.0  3.0  5

In [71]:
df.dropna(axis='rows') == df.dropna(axis = 0)

      0     1     2
1  True  True  True

In [72]:
df.dropna(axis='columns') == df.dropna(axis = 1 )

      2
0  True
1  True
2  True

In [73]:
df[3] = np.nan
df

     0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [74]:
df.dropna(axis='columns',how='all')

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [75]:
df.dropna(axis='rows',how='any')

Empty DataFrame
Columns: [0, 1, 2, 3]
Index: []

In [76]:
df.dropna(axis='rows', thresh = 3)

     0    1  2   3
1  2.0  3.0  5 NaN

### Filling null values

In [77]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde')) 
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [78]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [79]:
data.fillna(method='ffill'),data.fillna(method='bfill')

(a    1.0
 b    1.0
 c    2.0
 d    2.0
 e    3.0
 dtype: float64, a    1.0
 b    2.0
 c    2.0
 d    3.0
 e    3.0
 dtype: float64)

In [80]:
df

     0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [81]:
df.fillna(method='ffill',axis = 1)

     0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

In [82]:
df.fillna(method='bfill',axis = 1)

     0    1    2   3
0  1.0  2.0  2.0 NaN
1  2.0  3.0  5.0 NaN
2  4.0  4.0  6.0 NaN

In [83]:
df.fillna(method='ffill',axis = 0)

     0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  2.0  4.0  6 NaN

In [84]:
df.fillna(method='bfill',axis = 0)

     0    1  2   3
0  1.0  3.0  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

# Hierarchical Indexing

## A Multiply Indexed Series

In [0]:
 index = [('California', 2000), ('California', 2010),
          ('New York', 2000),('New York', 2010),
          ('Texas', 2000),('Texas', 2010)]
populations = [33871648, 37253956,
               18976457, 19378102,                      
               20851820, 25145561]

In [86]:
pop = pd.Series(populations,index = index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [87]:
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [88]:
pop = pop.reindex(index)
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [89]:
pop[:,2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

In [90]:
pop['California':'New York',2010]

TypeError: ignored

In [0]:
pop_df = pop.unstack()
pop_df

In [0]:
pop_df.stack()

In [0]:
 pop_df = pd.DataFrame({'total': pop,                               
                        'under18': [9267089, 9284094,
                                    4687374, 4318033,                                           
                                   5906301, 6879014]})
 pop_df

In [0]:
f_u18 = pop_df['under18']/pop_df['total']

In [0]:
f_u18.unstack()

## Methods of MultiIndex Creation

1. Simply pass a list of two or more index arrays to the constructor.

In [0]:
 df = pd.DataFrame(np.random.rand(4, 2),                          
                   index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]], 
                   columns=['data1', 'data2']) 
 df

2. Pass a dictionary with appropriate tuples as keys

In [0]:
 data = {('California', 2000): 33871648,
         ('California', 2010): 37253956,
         ('Texas', 2000): 20851820,
         ('Texas', 2010): 25145561,
         ('New York', 2000): 18976457,                
         ('New York', 2010): 19378102} 
pd.Series(data)

### Explicit MultiIndex constructors

In [0]:
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b'], [1, 2, 1, 2]])

In [0]:
pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2)])

In [0]:
pd.MultiIndex.from_product([['a', 'b'], [1, 2]])

In [0]:
 pd.MultiIndex(levels=[['a', 'b'], [1, 2]],
               codes=[[0, 0, 1, 1], [0, 1, 0, 1]])

### MultiIndex level names

In [0]:
pop.index.names = ['state','year']
pop

### MultiIndex for columns

In [91]:
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]],
                                   names=['year', 'visit'])
columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']],
                                     names=['subject', 'type'])


data = np.round(np.random.randn(4,6),1)
data[:,::2] *= 10
data +=37
health_data = pd.DataFrame(data,index= index,columns = columns)
health_data

subject      Bob       Guido         Sue
type          HR  Temp    HR  Temp    HR  Temp
year visit
2013 1      48.0  35.8  50.0  36.9  21.0  36.6
     2      32.0  35.8  43.0  35.7  35.0  37.5
2014 1      53.0  36.6  31.0  37.3  12.0  36.1
     2      33.0  36.1  46.0  37.4  45.0  36.1

In [92]:
health_data['Bob']

type          HR  Temp
year visit
2013 1      48.0  35.8
     2      32.0  35.8
2014 1      53.0  36.6
     2      33.0  36.1

### Indexing and Slicing a MultiIndex

In [93]:
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [94]:
pop['California',2000]

33871648

In [95]:
pop['California']

2000    33871648
2010    37253956
dtype: int64

In [96]:
pop.loc['California':'New York']

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
dtype: int64

In [97]:
pop[:,2000]

California    33871648
New York      18976457
Texas         20851820
dtype: int64

In [98]:
pop[pop > 22000000]

California  2000    33871648
            2010    37253956
Texas       2010    25145561
dtype: int64

In [99]:
 pop[['California', 'Texas']]

California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
dtype: int64

### Multiply indexed DataFrames

In [100]:
health_data['Guido','HR']

year  visit
2013  1        50.0
      2        43.0
2014  1        31.0
      2        46.0
Name: (Guido, HR), dtype: float64

In [101]:
health_data.iloc[:2,:3]

subject      Bob       Guido
type          HR  Temp    HR
year visit
2013 1      48.0  35.8  50.0
     2      32.0  35.8  43.0

In [102]:
 health_data.loc[:, ('Bob', 'HR')]

year  visit
2013  1        48.0
      2        32.0
2014  1        53.0
      2        33.0
Name: (Bob, HR), dtype: float64

In [103]:
 health_data.loc[(:, 1), (:, 'HR')]

SyntaxError: ignored

In [0]:
idx = pd.IndexSlice
idx

In [104]:
health_data.loc[idx[:,1],idx[:,'HR']]

NameError: ignored

## Rearranging Multi-Indices

### Sorted and unsorted indices
Many of the MultiIndex slicing operations will fail if the index is not sorted.

In [105]:
 index = pd.MultiIndex.from_product([['a', 'c', 'b'], [1, 2]])
 data = pd.Series(np.random.rand(6),index = index)
 data.index.names = ['char','int']
 data

char  int
a     1      0.623379
      2      0.745144
c     1      0.542212
      2      0.316759
b     1      0.009637
      2      0.430809
dtype: float64

In [106]:
try:
  data['a':'b']
except KeyError as e:
  print(type(e))
  print(e)

<class 'pandas.errors.UnsortedIndexError'>
'Key length (1) was greater than MultiIndex lexsort depth (0)'

In [107]:
data = data.sort_index()
data

char  int
a     1      0.623379
      2      0.745144
b     1      0.009637
      2      0.430809
c     1      0.542212
      2      0.316759
dtype: float64

In [108]:
data['a':'b']

char  int
a     1      0.623379
      2      0.745144
b     1      0.009637
      2      0.430809
dtype: float64

### Stacking and unstacking indices

In [109]:
pop.unstack(level = 0)

      California  New York     Texas
2000    33871648  18976457  20851820
2010    37253956  19378102  25145561

In [110]:
pop.unstack(level= 1)

                2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [111]:
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

### Index setting and resetting

In [0]:
#need specify name of the data for the column representation
pop_flat = pop.reset_index(name = "population")

In [113]:
pop_flat

      level_0  level_1  population
0  California     2000    33871648
1  California     2010    37253956
2    New York     2000    18976457
3    New York     2010    19378102
4       Texas     2000    20851820
5       Texas     2010    25145561

In [114]:
#return to multiindex
pop_flat.set_index(['state','year'])

KeyError: ignored

# Data aggregations on MultiIndeces

In [115]:
health_data

subject      Bob       Guido         Sue
type          HR  Temp    HR  Temp    HR  Temp
year visit
2013 1      48.0  35.8  50.0  36.9  21.0  36.6
     2      32.0  35.8  43.0  35.7  35.0  37.5
2014 1      53.0  36.6  31.0  37.3  12.0  36.1
     2      33.0  36.1  46.0  37.4  45.0  36.1

In [116]:
data_mean = health_data.mean(level='year')
data_mean

subject   Bob        Guido          Sue
type       HR   Temp    HR   Temp    HR   Temp
year
2013     40.0  35.80  46.5  36.30  28.0  37.05
2014     43.0  36.35  38.5  37.35  28.5  36.10

In [117]:
health_data.loc[2013,2].mean(axis = 0)

36.5

In [118]:
data_mean.mean(axis = 1,level='type')

type         HR       Temp
year
2013  38.166667  36.383333
2014  36.666667  36.600000

In [119]:
idx = pd.IndexSlice
health_data.loc[idx[:,1],idx[:,'HR']]

subject      Bob Guido   Sue
type          HR    HR    HR
year visit
2013 1      48.0  50.0  21.0
2014 1      53.0  31.0  12.0

In [120]:
health_data.loc[2013:2014]
health_data.loc[:,1]

KeyError: ignored

In [158]:
# only like this 
health_data.loc[idx[:,1],idx[:]]

subject      Bob       Guido         Sue
type          HR  Temp    HR  Temp    HR  Temp
year visit
2013 1      48.0  35.8  50.0  36.9  21.0  36.6
2014 1      53.0  36.6  31.0  37.3  12.0  36.1

In [159]:
health_data['Guido','HR']

year  visit
2013  1        50.0
      2        43.0
2014  1        31.0
      2        46.0
Name: (Guido, HR), dtype: float64

In [160]:
health_data.iloc[:3,:3]

subject      Bob       Guido
type          HR  Temp    HR
year visit
2013 1      48.0  35.8  50.0
     2      32.0  35.8  43.0
2014 1      53.0  36.6  31.0

In [161]:
health_data.loc[:,('Bob','HR')]

year  visit
2013  1        48.0
      2        32.0
2014  1        53.0
      2        33.0
Name: (Bob, HR), dtype: float64

# Combining Datasets: Concat and Append

In [0]:
def make_df(cols,ind):
  data = {c:[str(c) + str(i) for i in ind] for c in cols}
  return pd.DataFrame(data,ind)

In [163]:
make_df('ABC',range(3))

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

__pd.concat__

In [164]:
ser1 = pd.Series(['A','B','C'],index = [1,2,3])
ser2 = pd.Series(['D','E','F'],index=[4,5,6])
pd.concat([ser1,ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [165]:
df1 = make_df('AB',[1,2])
df2 = make_df('AB',[3,4])
print(df1);print(df2);print(pd.concat([df1,df2]))

    A   B
1  A1  B1
2  A2  B2
    A   B
3  A3  B3
4  A4  B4
    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

In [166]:
df3,df4 = make_df('AB',[0,1]),make_df('CD',[0,1])
print(df3);print(df4);print(pd.concat([df3,df4],axis = 1))

    A   B
0  A0  B0
1  A1  B1
    C   D
0  C0  D0
1  C1  D1
    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1

## __Duplicate indices__

In [167]:
x = make_df('AB',[0,1])
y  = make_df('AB',[0,1])
print(x);print(y);print(pd.concat([x,y]))

    A   B
0  A0  B0
1  A1  B1
    A   B
0  A0  B0
1  A1  B1
    A   B
0  A0  B0
1  A1  B1
0  A0  B0
1  A1  B1

### Catching the repeats

In [168]:
try:
  pd.concat([x,y],verify_integrity=True)
except ValueError as e:
  print("ValueError",e)

ValueError Indexes have overlapping values: Int64Index([0, 1], dtype='int64')

### Ignoring index

In [169]:
print(x);print(y);print(pd.concat([x,y],ignore_index=True))

    A   B
0  A0  B0
1  A1  B1
    A   B
0  A0  B0
1  A1  B1
    A   B
0  A0  B0
1  A1  B1
2  A0  B0
3  A1  B1

### Adding MultiIndex keys

In [170]:
print(x);print(y);print(pd.concat([x,y],keys = ['x','y']))

    A   B
0  A0  B0
1  A1  B1
    A   B
0  A0  B0
1  A1  B1
      A   B
x 0  A0  B0
  1  A1  B1
y 0  A0  B0
  1  A1  B1

### Concatenation with joins

In [171]:
df5 = make_df('ABC',[1,2])
df6 = make_df('BCD',[3,4])
print(df5);print(df6);print(pd.concat([df5,df6]))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2
    B   C   D
3  B3  C3  D3
4  B4  C4  D4
     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4

 By default, the join is a union of the input columns (join='outer'), but we can change this to an intersection of the columns using join='inner'

In [172]:
print(df5);print(df6);
print(pd.concat([df5,df6],join='inner'))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2
    B   C   D
3  B3  C3  D3
4  B4  C4  D4
    B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4

__append__()
append() method in Pandas does not modify the original object—instead, it creates a new object with the combined data. It also is not a very efficient method, because it involves creation of a new index and data buffer. Thus, if you plan to do multiple append operations, it is generally better to build a list of DataFrames and pass them all at once to the concat() function.

In [173]:
print(df1);print(df2);print(df1.append(df2))

    A   B
1  A1  B1
2  A2  B2
    A   B
3  A3  B3
4  A4  B4
    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

# __Combining Datasets: Merge and Join__
One essential feature offered by Pandas is its high-performance, in-memory join and merge operations

### one-to-one joins

In [174]:
df1 = pd.DataFrame({ 'employee':['Bob','Jake','Lisa','Sue'], 'group': ['Accounting','Engineering','Engineering','HR'] })
df2 = pd.DataFrame({ 'employee':['Lisa','Bob','Jake','Sue'],'hire_date':[2004,2008,2012,2014] })
print(df1);print(df2)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

In [175]:
df3 = pd.merge(df1,df2)
df3

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

## Many to one joins

In [176]:
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],'supervisor': ['Carly', 'Guido', 'Steve']})       
print(df3); print(df4); print(pd.merge(df3, df4))

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014
         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve
  employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve

## Many to many joins

In [0]:
df5 = pd.DataFrame({'group':['Acounting','Acounting','Engineering','Engineering','HR','HR'],'skills':['math','spreadsheets','coding','linux','spreadsheets','organization']})

In [178]:
print(df1);print(pd.merge(df1,df5))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
  employee        group        skills
0     Jake  Engineering        coding
1     Jake  Engineering         linux
2     Lisa  Engineering        coding
3     Lisa  Engineering         linux
4      Sue           HR  spreadsheets
5      Sue           HR  organization

## __Specification of Merge Key__

####the __on__ keyword

In [179]:
print(df1);print(df2);print(pd.merge(df1,df2,on="employee"))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014
  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

### __The left_on and right_on keywords__

In [0]:
df3 = pd.DataFrame({'name':['Bob','Jake','Lisa','Sue'],'salary':[70000,80000,120000,90000]})

In [181]:
print(df1);print(df3);print(pd.merge(df1,df3,left_on='employee',right_on='name'))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000
  employee        group  name  salary
0      Bob   Accounting   Bob   70000
1     Jake  Engineering  Jake   80000
2     Lisa  Engineering  Lisa  120000
3      Sue           HR   Sue   90000

### __left_index__ and __right_index__

In [182]:
df1a = df1.set_index('employee')
df2a = df2.set_index('employee')
print(df1a);print(df2a)

                group
employee
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR
          hire_date
employee
Lisa           2004
Bob            2008
Jake           2012
Sue            2014

In [183]:
print(pd.merge(df1a,df2a,left_index=True,right_index=True))

                group  hire_date
employee
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014

In [0]:
print(pd.merge(df1a,df2a,left_index=True,right_index=True))

For convenience, DataFrames implement the __join()__ method, which performs a merge that defaults to joining on indices

In [184]:
print(df1a);print(df2a);print(df1a.join(df2a))

                group
employee
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR
          hire_date
employee
Lisa           2004
Bob            2008
Jake           2012
Sue            2014
                group  hire_date
employee
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014

In [185]:
print(df1a);print(df3);print(pd.merge(df1a,df3,left_index=True,right_on='name'))

                group
employee
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR
   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000
         group  name  salary
0   Accounting   Bob   70000
1  Engineering  Jake   80000
2  Engineering  Lisa  120000
3           HR   Sue   90000

All of these options also work with multiple indices and/or multiple columns; the interface for this behavior is very intuitive. For more information on this, see the “Merge, Join, and Concatenate” section of the Pandas documentation.

Specifying Set Arithmetic for Joins

In [125]:
df6 = pd.DataFrame({'name':['Peter','Paul','Mary'],'food':['fish','beans','bread']},columns = ['name','food'])
df7 = pd.DataFrame({'name':['Mary','Joseph'],'drink':['wine','beer']},columns = ['name','drink'])
df6

    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread

In [126]:
df7

     name drink
0    Mary  wine
1  Joseph  beer

### Inner join

In [127]:
pd.merge(df6,df7) == pd.merge(df6,df7,how='inner')

   name  food  drink
0  True  True   True

An outer join returns a join over the union of the input columns, and fills in all missing values with NAs:

In [128]:
print(df6); print(df7);

    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread
     name drink
0    Mary  wine
1  Joseph  beer

In [129]:
print(pd.merge(df6, df7, how='outer'))

     name   food drink
0   Peter   fish   NaN
1    Paul  beans   NaN
2    Mary  bread  wine
3  Joseph    NaN  beer

In [130]:
print(df6); print(df7);

    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread
     name drink
0    Mary  wine
1  Joseph  beer

In [131]:
print(pd.merge(df6, df7, how='left'))

    name   food drink
0  Peter   fish   NaN
1   Paul  beans   NaN
2   Mary  bread  wine

In [132]:
print(pd.merge(df6, df7, how='right'))

     name   food drink
0    Mary  bread  wine
1  Joseph    NaN  beer

In [0]:
df8 = pd.DataFrame({'name':['Bob','Jake','Lisa','Sue'],'rank':[1,2,3,4]})

In [0]:
df9 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],                            
                    'rank': [3, 1, 4, 2]})

In [135]:
print(df8); print(df9)

   name  rank
0   Bob     1
1  Jake     2
2  Lisa     3
3   Sue     4
   name  rank
0   Bob     3
1  Jake     1
2  Lisa     4
3   Sue     2

In [136]:
print(pd.merge(df8, df9, on="name"))

   name  rank_x  rank_y
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2

#Two conflicting column names

In [137]:
print(df8);print(df9);
print(pd.merge(df8,df9,on='name',suffixes=['_L','_R']))

   name  rank
0   Bob     1
1  Jake     2
2  Lisa     3
3   Sue     4
   name  rank
0   Bob     3
1  Jake     1
2  Lisa     4
3   Sue     2
   name  rank_L  rank_R
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2

### __Example US States Data__

In [186]:
 !curl -O https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-population.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 57935  100 57935    0     0   152k      0 --:--:-- --:--:-- --:--:--  152k

In [187]:
 !curl -O https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-areas.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   835  100   835    0     0   2378      0 --:--:-- --:--:-- --:--:--  2378

In [188]:
 !curl -O https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-abbrevs.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   872  100   872    0     0   2247      0 --:--:-- --:--:-- --:--:--  2241

In [189]:
pop = pd.read_csv('state-population.csv')
pop

     state/region     ages  year   population
0              AL  under18  2012    1117489.0
1              AL    total  2012    4817528.0
2              AL  under18  2010    1130966.0
3              AL    total  2010    4785570.0
4              AL  under18  2011    1125763.0
...           ...      ...   ...          ...
2539          USA    total  2010  309326295.0
2540          USA  under18  2011   73902222.0
2541          USA    total  2011  311582564.0
2542          USA  under18  2012   73708179.0
2543          USA    total  2012  313873685.0

[2544 rows x 4 columns]

In [190]:
areas = pd.read_csv('state-areas.csv')
areas

                   state  area (sq. mi)
0                Alabama          52423
1                 Alaska         656425
2                Arizona         114006
3               Arkansas          53182
4             California         163707
5               Colorado         104100
6            Connecticut           5544
7               Delaware           1954
8                Florida          65758
9                Georgia          59441
10                Hawaii          10932
11                 Idaho          83574
12              Illinois          57918
13               Indiana          36420
14                  Iowa          56276
15                Kansas          82282
16              Kentucky          40411
17             Louisiana          51843
18                 Maine          35387
19              Maryland          12407
20         Massachusetts          10555
21              Michigan          96810
22             Minnesota          86943
23           Mississippi          48434
24              Missouri          69709
25               Montana         147046
26              Nebraska          77358
27                Nevada         110567
28         New Hampshire           9351
29            New Jersey           8722
30            New Mexico         121593
31              New York          54475
32        North Carolina          53821
33          North Dakota          70704
34                  Ohio          44828
35              Oklahoma          69903
36                Oregon          98386
37          Pennsylvania          46058
38          Rhode Island           1545
39        South Carolina          32007
40          South Dakota          77121
41             Tennessee          42146
42                 Texas         268601
43                  Utah          84904
44               Vermont           9615
45              Virginia          42769
46            Washington          71303
47         West Virginia          24231
48             Wisconsin          65503
49               Wyoming          97818
50  District of Columbia             68
51           Puerto Rico           3515

In [191]:
abbrevs = pd.read_csv('state-abbrevs.csv')
abbrevs

                   state abbreviation
0                Alabama           AL
1                 Alaska           AK
2                Arizona           AZ
3               Arkansas           AR
4             California           CA
5               Colorado           CO
6            Connecticut           CT
7               Delaware           DE
8   District of Columbia           DC
9                Florida           FL
10               Georgia           GA
11                Hawaii           HI
12                 Idaho           ID
13              Illinois           IL
14               Indiana           IN
15                  Iowa           IA
16                Kansas           KS
17              Kentucky           KY
18             Louisiana           LA
19                 Maine           ME
20               Montana           MT
21              Nebraska           NE
22                Nevada           NV
23         New Hampshire           NH
24            New Jersey           NJ
25            New Mexico           NM
26              New York           NY
27        North Carolina           NC
28          North Dakota           ND
29                  Ohio           OH
30              Oklahoma           OK
31                Oregon           OR
32              Maryland           MD
33         Massachusetts           MA
34              Michigan           MI
35             Minnesota           MN
36           Mississippi           MS
37              Missouri           MO
38          Pennsylvania           PA
39          Rhode Island           RI
40        South Carolina           SC
41          South Dakota           SD
42             Tennessee           TN
43                 Texas           TX
44                  Utah           UT
45               Vermont           VT
46              Virginia           VA
47            Washington           WA
48         West Virginia           WV
49             Wisconsin           WI
50               Wyoming           WY

In [144]:
merged = pd.merge(pop,abbrevs,how='outer',left_on='state/region',right_on = 'abbreviation')
merged = merged.drop('abbreviation',1)
merged.head()

  state/region     ages  year  population    state
0           AL  under18  2012   1117489.0  Alabama
1           AL    total  2012   4817528.0  Alabama
2           AL  under18  2010   1130966.0  Alabama
3           AL    total  2010   4785570.0  Alabama
4           AL  under18  2011   1125763.0  Alabama

In [145]:
merged.isnull().any()

state/region    False
ages            False
year            False
population       True
state            True
dtype: bool

In [146]:
merged[merged['population'].isnull()].head()

     state/region     ages  year  population state
2448           PR  under18  1990         NaN   NaN
2449           PR    total  1990         NaN   NaN
2450           PR    total  1991         NaN   NaN
2451           PR  under18  1991         NaN   NaN
2452           PR    total  1993         NaN   NaN

In [147]:
merged.loc[merged['state'].isnull(),'state/region'].unique()

array(['PR', 'USA'], dtype=object)

In [148]:
merged.loc[merged['state/region'] == 'PR', 'state'] = 'Puerto Rico' 
merged.loc[merged['state/region'] == 'USA', 'state'] = 'United States'
merged.isnull().any()

state/region    False
ages            False
year            False
population       True
state           False
dtype: bool

In [149]:
merged[merged['population'].isnull()].head()

     state/region     ages  year  population        state
2448           PR  under18  1990         NaN  Puerto Rico
2449           PR    total  1990         NaN  Puerto Rico
2450           PR    total  1991         NaN  Puerto Rico
2451           PR  under18  1991         NaN  Puerto Rico
2452           PR    total  1993         NaN  Puerto Rico

In [150]:
final = pd.merge(merged,areas,on='state',how='left')
final.head()

  state/region     ages  year  population    state  area (sq. mi)
0           AL  under18  2012   1117489.0  Alabama        52423.0
1           AL    total  2012   4817528.0  Alabama        52423.0
2           AL  under18  2010   1130966.0  Alabama        52423.0
3           AL    total  2010   4785570.0  Alabama        52423.0
4           AL  under18  2011   1125763.0  Alabama        52423.0

In [151]:
final.isnull().any()

state/region     False
ages             False
year             False
population        True
state            False
area (sq. mi)     True
dtype: bool

In [152]:
final['state'][final['area (sq. mi)'].isnull()].unique()

array(['United States'], dtype=object)

In [0]:
final.dropna(inplace = True)

In [154]:
final.head()

  state/region     ages  year  population    state  area (sq. mi)
0           AL  under18  2012   1117489.0  Alabama        52423.0
1           AL    total  2012   4817528.0  Alabama        52423.0
2           AL  under18  2010   1130966.0  Alabama        52423.0
3           AL    total  2010   4785570.0  Alabama        52423.0
4           AL  under18  2011   1125763.0  Alabama        52423.0

In [155]:
data2010 = final.query("year == 2010 & ages == 'total'")
data2010.head()

    state/region   ages  year  population       state  area (sq. mi)
3             AL  total  2010   4785570.0     Alabama        52423.0
91            AK  total  2010    713868.0      Alaska       656425.0
101           AZ  total  2010   6408790.0     Arizona       114006.0
189           AR  total  2010   2922280.0    Arkansas        53182.0
197           CA  total  2010  37333601.0  California       163707.0

In [0]:
data2010.set_index('state',inplace = True)
density = data2010['population'] / data2010['area (sq. mi)']

In [157]:
density.sort_values(ascending=False,inplace=True)
density.head()

state
District of Columbia    8898.897059
Puerto Rico             1058.665149
New Jersey              1009.253268
Rhode Island             681.339159
Connecticut              645.600649
dtype: float64

## Agregation and Grouping

### Planets Data

In [193]:
import seaborn as sns
planets = sns.load_dataset('planets')
planets.shape

(1035, 6)

In [195]:
planets.head()

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

### Simple Aggregation in Pandas

In [0]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.rand(5))

In [197]:
ser.sum(),ser.mean()

(2.811925491708157, 0.5623850983416314)

In [198]:
df = pd.DataFrame({'A':rng.rand(5),
                   'B':rng.rand(5)})

df

          A         B
0  0.155995  0.020584
1  0.058084  0.969910
2  0.866176  0.832443
3  0.601115  0.212339
4  0.708073  0.181825

In [199]:
df.mean()

A    0.477888
B    0.443420
dtype: float64

In [200]:
df.mean(axis = 0)

A    0.477888
B    0.443420
dtype: float64

In [201]:
df.mean(axis = 1)

0    0.088290
1    0.513997
2    0.849309
3    0.406727
4    0.444949
dtype: float64

In [208]:
planets.dropna().describe()

          number  orbital_period        mass    distance         year
count  498.00000      498.000000  498.000000  498.000000   498.000000
mean     1.73494      835.778671    2.509320   52.068213  2007.377510
std      1.17572     1469.128259    3.636274   46.596041     4.167284
min      1.00000        1.328300    0.003600    1.350000  1989.000000
25%      1.00000       38.272250    0.212500   24.497500  2005.000000
50%      1.00000      357.000000    1.245000   39.940000  2009.000000
75%      2.00000      999.600000    2.867500   59.332500  2011.000000
max      6.00000    17337.500000   25.000000  354.000000  2014.000000

### __Split, apply, combine__

In [0]:
dataFrame = pd.DataFrame({'key': ['A','B','C','A','B','C'],
                          'data':range(6)},columns = ['key','data'])

In [210]:
dataFrame

  key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [213]:
dataFrame.groupby('key').sum()

     data
key
A       3
B       5
C       7

#### __Column indexing__

In [0]:
grouped_planets = planets.groupby('method')

In [216]:
grouped_planets['orbital_period'].median()

method
Astrometry                         631.180000
Eclipse Timing Variations         4343.500000
Imaging                          27500.000000
Microlensing                      3300.000000
Orbital Brightness Modulation        0.342887
Pulsar Timing                       66.541900
Pulsation Timing Variations       1170.000000
Radial Velocity                    360.200000
Transit                              5.714932
Transit Timing Variations           57.011000
Name: orbital_period, dtype: float64

#### __Iteration over group__

Apply method is much more faster

In [217]:
for (method,group) in planets.groupby('method'):
  print('{0:30s} shape = {1}'.format(method,group.shape))

Astrometry                     shape = (2, 6)
Eclipse Timing Variations      shape = (9, 6)
Imaging                        shape = (38, 6)
Microlensing                   shape = (23, 6)
Orbital Brightness Modulation  shape = (3, 6)
Pulsar Timing                  shape = (5, 6)
Pulsation Timing Variations    shape = (1, 6)
Radial Velocity                shape = (553, 6)
Transit                        shape = (397, 6)
Transit Timing Variations      shape = (4, 6)

#### __Dispatch methods__

In [0]:
descr = planets.groupby('method')['year'].describe().unstack()

In [221]:
descr.T

       method
count  Astrometry                          2.0
       Eclipse Timing Variations           9.0
       Imaging                            38.0
       Microlensing                       23.0
       Orbital Brightness Modulation       3.0
                                         ...
max    Pulsar Timing                    2011.0
       Pulsation Timing Variations      2007.0
       Radial Velocity                  2014.0
       Transit                          2014.0
       Transit Timing Variations        2014.0
Length: 80, dtype: float64

## __Aggregate,filter,transform,apply__

In [0]:
rng = np.random.RandomState(0)
dataFrame = pd.DataFrame({'key': ['A','B','C','A','B','C'],
                          'data1':range(6),
                          'data2':rng.randint(0,10,6)},columns = ['key','data1','data2'])

In [223]:
dataFrame

  key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9

#### __Aggregation__

In [224]:
dataFrame.groupby('key').aggregate(['min',np.median,max])

    data1            data2
      min median max   min median max
key
A       0    1.5   3     3    4.0   5
B       1    2.5   4     0    3.5   7
C       2    3.5   5     3    6.0   9

In [225]:
dataFrame.groupby('key').aggregate({
    'data1':'min',
    'data2':'max'
})

     data1  data2
key
A        0      5
B        1      7
C        2      9

#### __Filtering__

In [227]:
def filter_func(x):
  return x['data2'].std() > 4

dataFrame

  key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9

In [228]:
dataFrame.groupby('key').std()

       data1     data2
key
A    2.12132  1.414214
B    2.12132  4.949747
C    2.12132  4.242641

In [229]:
dataFrame.groupby('key').filter(filter_func)

  key  data1  data2
1   B      1      0
2   C      2      3
4   B      4      7
5   C      5      9

#### __transformation__

In [230]:
dataFrame.groupby('key').transform(lambda x: x - x.mean())

   data1  data2
0   -1.5    1.0
1   -1.5   -3.5
2   -1.5   -3.0
3    1.5   -1.0
4    1.5    3.5
5    1.5    3.0

#### __apply__

In [231]:
def norm_by_data2(x):
  x['data1'] /= x['data2'].sum()
  return x
dataFrame.groupby('key').apply(norm_by_data2)

  key     data1  data2
0   A  0.000000      5
1   B  0.142857      0
2   C  0.166667      3
3   A  0.375000      3
4   B  0.571429      7
5   C  0.416667      9